# render.yaml
services:
  - type: web
    name: emr-frontend
    env: static
    buildCommand: cd emr-frontend && npm install && npm run build  # Adjust if repo root
    staticPublishPath: emr-frontend/build  # Adjust if repo root
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
