# render.yaml (in emr_app/)
services:
  - type: web
    name: emr-frontend
    env: static
    buildCommand: cd emr-frontend && npm install && npm run build
    staticPublishPath: emr-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
